### ISSUE TITLE
Have you tried to use FROM mcr.microsoft.com/windows/nanocore:ltsc2019 instead of servercore

### ISSUE THREAD

**Issue by yangxinyun** [bgsilvait/k8s-fluentd-windows#2]
Hi,

Any specific reason of not using nano server image?

This can dramatically shrink the image size.

Regards

**Comment by bgsilvait** [comment]
The last time I took a look, the nano server did not support ruby, so not able to install the binaries for Fluent.

I'll start soon a plan to move this project to Fluentbit

**Comment by yangxinyun** [comment]
Hi,

Thanks for getting back.  Fluentbit sounds more a promising plan indeed.

Look forward to hearing from your Fluentbit.

Thanks
